### ISSUE TITLE
Please do 1.18.2 also, can you configure which items?

### ISSUE THREAD

**Issue by Aceplante** [Xaikii/GunAndRun#1]
please do forge 1.18.2 also is it possible to configure the speed decrease when eating food or using potions etc?

**Comment by Xaikii** [comment]
I had no plans for 1.18, but I'll see :)

And yes, you can configure individual items in the config, I gave an example there

**Comment by Xaikii** [comment]
Just uploaded on CurseForge, will be available shortly

**Comment by Aceplante** [comment]
much appreciated will try it later
